repos:
  # Docker hooks
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.0
    hooks:
      - id: docker-compose-check
  # Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        types_or: [markdown, dockerfile, dockerignore, gitignore, yaml]
  # Isort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  # Black
  - repo: https://github.com/psf/black.git
    rev: 22.3.0
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]
  # Flake 8
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
  # Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        language_version: python
        args:
          - --namespace-packages
          - --explicit-package-bases
          - --ignore-missing-imports
